- name: Login to Amazon ECR
  id: login-ecr
  uses: aws-actions/amazon-ecr-login@v2

- name: Build, tag, and push Docker image to Amazon ECR
  run: |
    # Set environment variables
    REGISTRY=688567261103.dkr.ecr.eu-north-1.amazonaws.com
    REPOSITORY=aiops

    # Build and push the Docker image
    docker build -t aiops/main.py:latest .
    docker push aiops/main.py:latest
